In [127]:
import pandas as pd
import numpy as np

In [128]:
df = pd.read_excel("/content/T_ONTIME_REPORTING.xlsx", engine='openpyxl')

In [129]:
df

,FL_DATE,OP_UNIQUE_CARRIER,TAIL_NUM,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_NM,DEST_AIRPORT_ID,DEST,...,DEP_DEL15,TAXI_OUT,CRS_ARR_TIME,ARR_DELAY,ARR_DEL15,ARR_TIME_BLK,CANCELLED,CANCELLATION_CODE,ACTUAL_ELAPSED_TIME,DISTANCE
0,2026-01-01,AA,N101NN,1480,12892,LAX,"Los Angeles, CA",California,10721,BOS,...,1.0,14.0,2229,59.0,1.0,2200-2259,0,NaN,305.0,2611
1,2026-01-01,AA,N101NN,255,12478,JFK,"New York, NY",New York,12892,LAX,...,1.0,47.0,1303,86.0,1.0,1300-1359,0,NaN,397.0,2475
2,2026-01-01,AA,N103NN,2453,12892,LAX,"Los Angeles, CA",California,10721,BOS,...,1.0,30.0,628,19.0,1.0,0600-0659,0,NaN,320.0,2611
3,2026-01-01,AA,N103NN,302,12478,JFK,"New York, NY",New York,12892,LAX,...,0.0,29.0,2100,21.0,1.0,2100-2159,0,NaN,395.0,2475
4,2026-01-01,AA,N103NN,307,12892,LAX,"Los Angeles, CA",California,12478,JFK,...,0.0,12.0,1654,-22.0,0.0,1600-1659,0,NaN,302.0,2475
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
543998,2026-01-31,YX,N879RW,5809,14730,SDF,"Louisville, KY",Kentucky,11433,DTW,...,0.0,34.0,1209,28.0,1.0,1200-1259,0,NaN,110.0,306
543999,2026-01-31,YX,N879RW,5841,11433,DTW,"Detroit, MI",Michigan,14122,PIT,...,1.0,26.0,1405,14.0,0.0,1400-1459,0,NaN,72.0,201
544000,2026-01-31,YX,N879RW,5841,14122,PIT,"Pittsburgh, PA",Pennsylvania,11433,DTW,...,0.0,15.0,1611,-17.0,0.0,1600-1659,0,NaN,66.0,201
544001,2026-01-31,YX,N979RP,4459,14492,RDU,"Raleigh/Durham, NC",North Carolina,12953,LGA,...,NaN,NaN,1844,NaN,NaN,1800-1859,1,B,NaN,431
544002,2026-01-31,YX,N979RP,4497,12953,LGA,"New York, NY",New York,14492,RDU,...,NaN,NaN,1631,NaN,NaN,1600-1659,1,B,NaN,431

#Exploring Dataset

In [130]:
df.shape

(544003, 24)

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 544003 entries, 0 to 544002
Data columns (total 24 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   FL_DATE              544003 non-null  datetime64[ns]
 1   OP_UNIQUE_CARRIER    544003 non-null  object
 2   TAIL_NUM             539365 non-null  object
 3   OP_CARRIER_FL_NUM    544003 non-null  int64
 4   ORIGIN_AIRPORT_ID    544003 non-null  int64
 5   ORIGIN               544003 non-null  object
 6   ORIGIN_CITY_NAME     544003 non-null  object
 7   ORIGIN_STATE_NM      544003 non-null  object
 8   DEST_AIRPORT_ID      544003 non-null  int64
 9   DEST                 544003 non-null  object
 10  DEST_CITY_NAME       544003 non-null  object
 11  DEST_STATE_NM        544003 non-null  object
 12  CRS_DEP_TIME         544003 non-null  int64
 13  DEP_DELAY            518774 non-null  float64
 14  DEP_DEL15            518774 non-null  float64
 15  TAXI_OUT             518488 non-null  float64
 16  CRS_ARR_TIME         544003 non-null  int64
 17  ARR_DELAY            517222 non-null  float64
 18  ARR_DEL15            517222 non-null  float64
 19  ARR_TIME_BLK         544003 non-null  object
 20  CANCELLED            544003 non-null  int64
 21  CANCELLATION_CODE    25635 non-null   object
 22  ACTUAL_ELAPSED_TIME  517222 non-null  float64
 23  DISTANCE             544003 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(7), object(10)
memory usage: 99.6+ MB

In [132]:
df.describe()

,FL_DATE,OP_CARRIER_FL_NUM,ORIGIN_AIRPORT_ID,DEST_AIRPORT_ID,CRS_DEP_TIME,DEP_DELAY,DEP_DEL15,TAXI_OUT,CRS_ARR_TIME,ARR_DELAY,ARR_DEL15,CANCELLED,ACTUAL_ELAPSED_TIME,DISTANCE
count,544003,544003.000000,544003.000000,544003.000000,544003.000000,518774.000000,518774.000000,518488.000000,544003.000000,517222.00000,517222.000000,544003.000000,517222.000000,544003.000000
mean,2026-01-15 18:35:25.325043968,2543.130141,12680.789312,12680.593587,1312.949737,13.096535,0.206828,19.402945,1507.982257,6.41036,0.207793,0.047123,146.302708,846.648487
min,2026-01-01 00:00:00,1.000000,10135.000000,10135.000000,2.000000,-59.000000,0.000000,1.000000,1.000000,-85.00000,0.000000,0.000000,17.000000,31.000000
25%,2026-01-08 00:00:00,1217.000000,11292.000000,11292.000000,905.000000,-6.000000,0.000000,13.000000,1120.000000,-18.00000,0.000000,0.000000,92.000000,404.000000
50%,2026-01-16 00:00:00,2279.000000,12889.000000,12889.000000,1310.000000,-2.000000,0.000000,16.000000,1525.000000,-7.00000,0.000000,0.000000,130.000000,704.000000
75%,2026-01-24 00:00:00,3707.000000,14057.000000,14057.000000,1719.000000,9.000000,0.000000,22.000000,1923.000000,9.00000,0.000000,0.000000,179.000000,1083.000000
max,2026-01-31 00:00:00,9914.000000,16869.000000,16869.000000,2359.000000,3339.000000,1.000000,213.000000,2359.000000,3339.00000,1.000000,1.000000,763.000000,4983.000000
std,NaN,1637.303970,1529.123118,1529.063826,477.706974,60.968480,0.405031,11.613879,495.444276,63.39614,0.405728,0.211902,74.490579,603.771438

In [133]:
df.duplicated().sum()

np.int64(0)

In [134]:
df.isnull().sum()

FL_DATE                     0
OP_UNIQUE_CARRIER           0
TAIL_NUM                 4638
OP_CARRIER_FL_NUM           0
ORIGIN_AIRPORT_ID           0
ORIGIN                      0
ORIGIN_CITY_NAME            0
ORIGIN_STATE_NM             0
DEST_AIRPORT_ID             0
DEST                        0
DEST_CITY_NAME              0
DEST_STATE_NM               0
CRS_DEP_TIME                0
DEP_DELAY               25229
DEP_DEL15               25229
TAXI_OUT                25515
CRS_ARR_TIME                0
ARR_DELAY               26781
ARR_DEL15               26781
ARR_TIME_BLK                0
CANCELLED                   0
CANCELLATION_CODE      518368
ACTUAL_ELAPSED_TIME     26781
DISTANCE                    0
dtype: int64

#Cleaning Data

FL_DATE

In [135]:
 # Remove 0:00 from the date
df["FL_DATE"] = pd.to_datetime(df["FL_DATE"]).dt.date
df["FL_DATE"] = pd.to_datetime(df["FL_DATE"])
df["FL_DATE"]

0        2026-01-01
1        2026-01-01
2        2026-01-01
3        2026-01-01
4        2026-01-01
            ...
543998   2026-01-31
543999   2026-01-31
544000   2026-01-31
544001   2026-01-31
544002   2026-01-31
Name: FL_DATE, Length: 544003, dtype: datetime64[ns]

OP_UNIQUE_CARRIER

In [136]:
carrier_names = {
    "AA": "American Airlines",
    "AS": "Alaska Airlines",
    "B6": "JetBlue Airways",
    "DL": "Delta Air Lines",
    "F9": "Frontier Airlines",
    "G4": "Allegiant Air",
    "HA": "Hawaiian Airlines",
    "MQ": "Envoy Air",
    "NK": "Spirit Airlines",
    "OH": "PSA Airlines",
    "OO": "SkyWest Airlines",
    "UA": "United Airlines",
    "WN": "Southwest Airlines",
    "YX": "Republic Airways"
}

df["OP_UNIQUE_CARRIER"] = df["OP_UNIQUE_CARRIER"].replace(carrier_names)

In [137]:
df["OP_UNIQUE_CARRIER"]

0         American Airlines
1         American Airlines
2         American Airlines
3         American Airlines
4         American Airlines
                ...
543998     Republic Airways
543999     Republic Airways
544000     Republic Airways
544001     Republic Airways
544002     Republic Airways
Name: OP_UNIQUE_CARRIER, Length: 544003, dtype: object

TAIL_NUM

In [138]:
df["TAIL_NUM"] = df["TAIL_NUM"].fillna("Unknown")
df.isnull().sum()

FL_DATE                     0
OP_UNIQUE_CARRIER           0
TAIL_NUM                    0
OP_CARRIER_FL_NUM           0
ORIGIN_AIRPORT_ID           0
ORIGIN                      0
ORIGIN_CITY_NAME            0
ORIGIN_STATE_NM             0
DEST_AIRPORT_ID             0
DEST                        0
DEST_CITY_NAME              0
DEST_STATE_NM               0
CRS_DEP_TIME                0
DEP_DELAY               25229
DEP_DEL15               25229
TAXI_OUT                25515
CRS_ARR_TIME                0
ARR_DELAY               26781
ARR_DEL15               26781
ARR_TIME_BLK                0
CANCELLED                   0
CANCELLATION_CODE      518368
ACTUAL_ELAPSED_TIME     26781
DISTANCE                    0
dtype: int64

ORIGIN_CITY_NAME

In [139]:
# Keep city name only
df["ORIGIN_CITY_NAME"] = (
    df["ORIGIN_CITY_NAME"]
    .astype(str)
    .str.split(",")
    .str[0]
    .str.strip()
)

In [140]:
df["ORIGIN_CITY_NAME"]

0            Los Angeles
1               New York
2            Los Angeles
3               New York
4            Los Angeles
               ...
543998        Louisville
543999           Detroit
544000        Pittsburgh
544001    Raleigh/Durham
544002          New York
Name: ORIGIN_CITY_NAME, Length: 544003, dtype: object

DEST_CITY_NAME

In [141]:
# Keep city name only
df["DEST_CITY_NAME"] = (
    df["DEST_CITY_NAME"]
    .astype(str)
    .str.split(",")
    .str[0]
    .str.strip()
)

In [142]:
df["DEST_CITY_NAME"]

0                 Boston
1            Los Angeles
2                 Boston
3            Los Angeles
4               New York
               ...
543998           Detroit
543999        Pittsburgh
544000           Detroit
544001          New York
544002    Raleigh/Durham
Name: DEST_CITY_NAME, Length: 544003, dtype: object

DEP_DELAY

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 544003 entries, 0 to 544002
Data columns (total 24 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   FL_DATE              544003 non-null  datetime64[ns]
 1   OP_UNIQUE_CARRIER    544003 non-null  object
 2   TAIL_NUM             544003 non-null  object
 3   OP_CARRIER_FL_NUM    544003 non-null  int64
 4   ORIGIN_AIRPORT_ID    544003 non-null  int64
 5   ORIGIN               544003 non-null  object
 6   ORIGIN_CITY_NAME     544003 non-null  object
 7   ORIGIN_STATE_NM      544003 non-null  object
 8   DEST_AIRPORT_ID      544003 non-null  int64
 9   DEST                 544003 non-null  object
 10  DEST_CITY_NAME       544003 non-null  object
 11  DEST_STATE_NM        544003 non-null  object
 12  CRS_DEP_TIME         544003 non-null  int64
 13  DEP_DELAY            518774 non-null  float64
 14  DEP_DEL15            518774 non-null  float64
 15  TAXI_OUT             518488 non-null  float64
 16  CRS_ARR_TIME         544003 non-null  int64
 17  ARR_DELAY            517222 non-null  float64
 18  ARR_DEL15            517222 non-null  float64
 19  ARR_TIME_BLK         544003 non-null  object
 20  CANCELLED            544003 non-null  int64
 21  CANCELLATION_CODE    25635 non-null   object
 22  ACTUAL_ELAPSED_TIME  517222 non-null  float64
 23  DISTANCE             544003 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(7), object(10)
memory usage: 99.6+ MB

In [144]:
#Replace missing values with Median
df["DEP_DELAY"] = df["DEP_DELAY"].fillna(df["DEP_DELAY"].median())
df['DEP_DELAY'] = df['DEP_DELAY'].astype('int64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 544003 entries, 0 to 544002
Data columns (total 24 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   FL_DATE              544003 non-null  datetime64[ns]
 1   OP_UNIQUE_CARRIER    544003 non-null  object
 2   TAIL_NUM             544003 non-null  object
 3   OP_CARRIER_FL_NUM    544003 non-null  int64
 4   ORIGIN_AIRPORT_ID    544003 non-null  int64
 5   ORIGIN               544003 non-null  object
 6   ORIGIN_CITY_NAME     544003 non-null  object
 7   ORIGIN_STATE_NM      544003 non-null  object
 8   DEST_AIRPORT_ID      544003 non-null  int64
 9   DEST                 544003 non-null  object
 10  DEST_CITY_NAME       544003 non-null  object
 11  DEST_STATE_NM        544003 non-null  object
 12  CRS_DEP_TIME         544003 non-null  int64
 13  DEP_DELAY            544003 non-null  int64
 14  DEP_DEL15            518774 non-null  float64
 15  TAXI_OUT             518488 non-null  float64
 16  CRS_ARR_TIME         544003 non-null  int64
 17  ARR_DELAY            517222 non-null  float64
 18  ARR_DEL15            517222 non-null  float64
 19  ARR_TIME_BLK         544003 non-null  object
 20  CANCELLED            544003 non-null  int64
 21  CANCELLATION_CODE    25635 non-null   object
 22  ACTUAL_ELAPSED_TIME  517222 non-null  float64
 23  DISTANCE             544003 non-null  int64
dtypes: datetime64[ns](1), float64(5), int64(8), object(10)
memory usage: 99.6+ MB

DEP_DEL15

In [145]:
pd.value_counts(df["DEP_DEL15"])

/tmp/ipykernel_2124/4165805065.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(df["DEP_DEL15"])

DEP_DEL15
0.0    411477
1.0    107297
Name: count, dtype: int64

In [146]:
#Fill missing values based on DEP_DELAY Median
df.loc[df["DEP_DELAY"] >= 15, "DEP_DEL15"] = 1
df.loc[df["DEP_DELAY"] < 15, "DEP_DEL15"] = 0
df["DEP_DEL15"]

0         1.0
1         1.0
2         1.0
3         0.0
4         0.0
         ...
543998    0.0
543999    1.0
544000    0.0
544001    0.0
544002    0.0
Name: DEP_DEL15, Length: 544003, dtype: float64

In [147]:
pd.value_counts(df["DEP_DEL15"])

/tmp/ipykernel_2124/4165805065.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(df["DEP_DEL15"])

DEP_DEL15
0.0    436706
1.0    107297
Name: count, dtype: int64

 ARR_DELAY

In [148]:
# Replace missing values with Median
df["ARR_DELAY"] = df["ARR_DELAY"].fillna(df["ARR_DELAY"].median())
df['ARR_DELAY'] = df['ARR_DELAY'].astype('int64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 544003 entries, 0 to 544002
Data columns (total 24 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   FL_DATE              544003 non-null  datetime64[ns]
 1   OP_UNIQUE_CARRIER    544003 non-null  object
 2   TAIL_NUM             544003 non-null  object
 3   OP_CARRIER_FL_NUM    544003 non-null  int64
 4   ORIGIN_AIRPORT_ID    544003 non-null  int64
 5   ORIGIN               544003 non-null  object
 6   ORIGIN_CITY_NAME     544003 non-null  object
 7   ORIGIN_STATE_NM      544003 non-null  object
 8   DEST_AIRPORT_ID      544003 non-null  int64
 9   DEST                 544003 non-null  object
 10  DEST_CITY_NAME       544003 non-null  object
 11  DEST_STATE_NM        544003 non-null  object
 12  CRS_DEP_TIME         544003 non-null  int64
 13  DEP_DELAY            544003 non-null  int64
 14  DEP_DEL15            544003 non-null  float64
 15  TAXI_OUT             518488 non-null  float64
 16  CRS_ARR_TIME         544003 non-null  int64
 17  ARR_DELAY            544003 non-null  int64
 18  ARR_DEL15            517222 non-null  float64
 19  ARR_TIME_BLK         544003 non-null  object
 20  CANCELLED            544003 non-null  int64
 21  CANCELLATION_CODE    25635 non-null   object
 22  ACTUAL_ELAPSED_TIME  517222 non-null  float64
 23  DISTANCE             544003 non-null  int64
dtypes: datetime64[ns](1), float64(4), int64(9), object(10)
memory usage: 99.6+ MB

ARR_DEL15

In [149]:
pd.value_counts(df["ARR_DEL15"])

/tmp/ipykernel_2124/3851331345.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(df["ARR_DEL15"])

ARR_DEL15
0.0    409747
1.0    107475
Name: count, dtype: int64

In [150]:
# Fill missing values based on ARR_DELAY Median
df.loc[df["ARR_DELAY"] >= 15, "ARR_DEL15"] = 1
df.loc[df["ARR_DELAY"] < 15, "ARR_DEL15"] = 0
df["ARR_DEL15"]

0         1.0
1         1.0
2         1.0
3         1.0
4         0.0
         ...
543998    1.0
543999    0.0
544000    0.0
544001    0.0
544002    0.0
Name: ARR_DEL15, Length: 544003, dtype: float64

In [151]:
pd.value_counts(df["ARR_DEL15"])

/tmp/ipykernel_2124/3851331345.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(df["ARR_DEL15"])

ARR_DEL15
0.0    436528
1.0    107475
Name: count, dtype: int64

TAXI_OUT

In [152]:
# Replace missing values with Mean
df["TAXI_OUT"] = df["TAXI_OUT"].fillna(df["TAXI_OUT"].mean())
df.isnull().sum()

FL_DATE                     0
OP_UNIQUE_CARRIER           0
TAIL_NUM                    0
OP_CARRIER_FL_NUM           0
ORIGIN_AIRPORT_ID           0
ORIGIN                      0
ORIGIN_CITY_NAME            0
ORIGIN_STATE_NM             0
DEST_AIRPORT_ID             0
DEST                        0
DEST_CITY_NAME              0
DEST_STATE_NM               0
CRS_DEP_TIME                0
DEP_DELAY                   0
DEP_DEL15                   0
TAXI_OUT                    0
CRS_ARR_TIME                0
ARR_DELAY                   0
ARR_DEL15                   0
ARR_TIME_BLK                0
CANCELLED                   0
CANCELLATION_CODE      518368
ACTUAL_ELAPSED_TIME     26781
DISTANCE                    0
dtype: int64

CANCELLATION_CODE

In [153]:
# Drop columns
df = df.drop(
    columns=["CANCELLATION_CODE"]
)
df.columns

Index(['FL_DATE', 'OP_UNIQUE_CARRIER', 'TAIL_NUM', 'OP_CARRIER_FL_NUM',
       'ORIGIN_AIRPORT_ID', 'ORIGIN', 'ORIGIN_CITY_NAME', 'ORIGIN_STATE_NM',
       'DEST_AIRPORT_ID', 'DEST', 'DEST_CITY_NAME', 'DEST_STATE_NM',
       'CRS_DEP_TIME', 'DEP_DELAY', 'DEP_DEL15', 'TAXI_OUT', 'CRS_ARR_TIME',
       'ARR_DELAY', 'ARR_DEL15', 'ARR_TIME_BLK', 'CANCELLED',
       'ACTUAL_ELAPSED_TIME', 'DISTANCE'],
      dtype='object')

ACTUAL_ELAPSED_TIME

In [154]:
# Replace missing values with Median
df["ACTUAL_ELAPSED_TIME"] = df["ACTUAL_ELAPSED_TIME"].fillna(df["ACTUAL_ELAPSED_TIME"].median())
df['ACTUAL_ELAPSED_TIME'] = df['ACTUAL_ELAPSED_TIME'].astype('int64')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 544003 entries, 0 to 544002
Data columns (total 23 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   FL_DATE              544003 non-null  datetime64[ns]
 1   OP_UNIQUE_CARRIER    544003 non-null  object
 2   TAIL_NUM             544003 non-null  object
 3   OP_CARRIER_FL_NUM    544003 non-null  int64
 4   ORIGIN_AIRPORT_ID    544003 non-null  int64
 5   ORIGIN               544003 non-null  object
 6   ORIGIN_CITY_NAME     544003 non-null  object
 7   ORIGIN_STATE_NM      544003 non-null  object
 8   DEST_AIRPORT_ID      544003 non-null  int64
 9   DEST                 544003 non-null  object
 10  DEST_CITY_NAME       544003 non-null  object
 11  DEST_STATE_NM        544003 non-null  object
 12  CRS_DEP_TIME         544003 non-null  int64
 13  DEP_DELAY            544003 non-null  int64
 14  DEP_DEL15            544003 non-null  float64
 15  TAXI_OUT             544003 non-null  float64
 16  CRS_ARR_TIME         544003 non-null  int64
 17  ARR_DELAY            544003 non-null  int64
 18  ARR_DEL15            544003 non-null  float64
 19  ARR_TIME_BLK         544003 non-null  object
 20  CANCELLED            544003 non-null  int64
 21  ACTUAL_ELAPSED_TIME  544003 non-null  int64
 22  DISTANCE             544003 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(10), object(9)
memory usage: 95.5+ MB

CRS_DEP_TIME

In [155]:
# Convert CRS_DEP_TIME to HH:MM
def convert_time(value):
    if pd.isna(value):
        return np.nan

    value = int(value)

    hour = value // 100
    minute = value % 100

    return f"{hour:02d}:{minute:02d}"


df["CRS_DEP_TIME"] = df["CRS_DEP_TIME"].apply(convert_time)

In [156]:
df["CRS_DEP_TIME"]

0         13:58
1         09:41
2         22:00
3         17:45
4         08:30
          ...
543998    10:41
543999    12:49
544000    14:50
544001    17:02
544002    14:31
Name: CRS_DEP_TIME, Length: 544003, dtype: object

CRS_ARR_TIME

In [157]:
# 13. Convert CRS_ARR_TIME to HH:MM
df["CRS_ARR_TIME"] = df["CRS_ARR_TIME"].apply(convert_time)

In [158]:
df["CRS_ARR_TIME"]

0         22:29
1         13:03
2         06:28
3         21:00
4         16:54
          ...
543998    12:09
543999    14:05
544000    16:11
544001    18:44
544002    16:31
Name: CRS_ARR_TIME, Length: 544003, dtype: object

ARR_TIME_BLK

In [159]:
# Convert ARR_TIME_BLK
# Example: 2200-2259 -> 22:00-22:59
def convert_time_block(value):

    if pd.isna(value):
        return np.nan

    value = str(value)

    start, end = value.split("-")

    start_time = convert_time(int(start))
    end_time = convert_time(int(end))

    return f"{start_time}-{end_time}"


df["ARR_TIME_BLK"] = df["ARR_TIME_BLK"].apply(
    convert_time_block
)

In [160]:
df["ARR_TIME_BLK"]

0         22:00-22:59
1         13:00-13:59
2         06:00-06:59
3         21:00-21:59
4         16:00-16:59
             ...
543998    12:00-12:59
543999    14:00-14:59
544000    16:00-16:59
544001    18:00-18:59
544002    16:00-16:59
Name: ARR_TIME_BLK, Length: 544003, dtype: object

Rename Columns

In [161]:
df = df.rename(columns={
    "OP_UNIQUE_CARRIER": "Operating Carrier",
    "TAIL_NUM": "Aircraft Tail Number",
    "CRS_DEP_TIME": "Scheduled Departure Time",
    "DEP_DEL15": "Departure Delay ≥ 15 Minutes",
    "CRS_ARR_TIME": "Scheduled Arrival Time",
    "ARR_DEL15": "Arrival Delay ≥ 15 Minutes",
    "ARR_TIME_BLK": "Arrival Time Block"
})

In [162]:
df.columns

Index(['FL_DATE', 'Operating Carrier', 'Aircraft Tail Number',
       'OP_CARRIER_FL_NUM', 'ORIGIN_AIRPORT_ID', 'ORIGIN', 'ORIGIN_CITY_NAME',
       'ORIGIN_STATE_NM', 'DEST_AIRPORT_ID', 'DEST', 'DEST_CITY_NAME',
       'DEST_STATE_NM', 'Scheduled Departure Time', 'DEP_DELAY',
       'Departure Delay ≥ 15 Minutes', 'TAXI_OUT', 'Scheduled Arrival Time',
       'ARR_DELAY', 'Arrival Delay ≥ 15 Minutes', 'Arrival Time Block',
       'CANCELLED', 'ACTUAL_ELAPSED_TIME', 'DISTANCE'],
      dtype='object')

In [163]:
df.isnull().sum()

FL_DATE                         0
Operating Carrier               0
Aircraft Tail Number            0
OP_CARRIER_FL_NUM               0
ORIGIN_AIRPORT_ID               0
ORIGIN                          0
ORIGIN_CITY_NAME                0
ORIGIN_STATE_NM                 0
DEST_AIRPORT_ID                 0
DEST                            0
DEST_CITY_NAME                  0
DEST_STATE_NM                   0
Scheduled Departure Time        0
DEP_DELAY                       0
Departure Delay ≥ 15 Minutes    0
TAXI_OUT                        0
Scheduled Arrival Time          0
ARR_DELAY                       0
Arrival Delay ≥ 15 Minutes      0
Arrival Time Block              0
CANCELLED                       0
ACTUAL_ELAPSED_TIME             0
DISTANCE                        0
dtype: int64

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 544003 entries, 0 to 544002
Data columns (total 23 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   FL_DATE                       544003 non-null  datetime64[ns]
 1   Operating Carrier             544003 non-null  object
 2   Aircraft Tail Number          544003 non-null  object
 3   OP_CARRIER_FL_NUM             544003 non-null  int64
 4   ORIGIN_AIRPORT_ID             544003 non-null  int64
 5   ORIGIN                        544003 non-null  object
 6   ORIGIN_CITY_NAME              544003 non-null  object
 7   ORIGIN_STATE_NM               544003 non-null  object
 8   DEST_AIRPORT_ID               544003 non-null  int64
 9   DEST                          544003 non-null  object
 10  DEST_CITY_NAME                544003 non-null  object
 11  DEST_STATE_NM                 544003 non-null  object
 12  Scheduled Departure Time      544003 non-null  object
 13  DEP_DELAY                     544003 non-null  int64
 14  Departure Delay ≥ 15 Minutes  544003 non-null  float64
 15  TAXI_OUT                      544003 non-null  float64
 16  Scheduled Arrival Time        544003 non-null  object
 17  ARR_DELAY                     544003 non-null  int64
 18  Arrival Delay ≥ 15 Minutes    544003 non-null  float64
 19  Arrival Time Block            544003 non-null  object
 20  CANCELLED                     544003 non-null  int64
 21  ACTUAL_ELAPSED_TIME           544003 non-null  int64
 22  DISTANCE                      544003 non-null  int64
dtypes: datetime64[ns](1), float64(3), int64(8), object(11)
memory usage: 95.5+ MB

Change Data Type

In [165]:
df["OP_CARRIER_FL_NUM"] = df["OP_CARRIER_FL_NUM"].astype(str)
df["ORIGIN_AIRPORT_ID"] = df["ORIGIN_AIRPORT_ID"].astype(str)
df["DEST_AIRPORT_ID"] = df["DEST_AIRPORT_ID"].astype(str)
df["Departure Delay ≥ 15 Minutes"] = (
    df["Departure Delay ≥ 15 Minutes"].astype(int)
)
df["Arrival Delay ≥ 15 Minutes"] = (
    df["Arrival Delay ≥ 15 Minutes"].astype(int)
)

In [166]:
df.to_csv(
    "cleaned_flight_data.csv",
    index=False
)